language: python
python:
 - "3.5"
 - "3.7"

install:
 - pip install -r requirements.txt
 - pip install pylama
 # Check if pylama was installed correctly
 - pylama --version

script:
 # Is that code OK? Execute code linters
 - pylama --async --sort E,W,D
 # Execute tests
 - python -m unittest
